/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-64-g01b75fc+01b75fc281d67d1ad2859311abb4db93b43368ca

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: ZEDBoxMini_V3.xdd
        File Version: 1

        Created:      07.02.2026 08:57:00
        Created By:   CODESYS V3.X, DeviceEditorCANbusDevice.plugin, V3.5.11.0
        Modified:     07.02.2026 09:00:32
        Modified By:  CODESYS V3.X, DeviceEditorCANbusDevice.plugin, V3.5.11.0

    Device Info:
        Vendor Name:  SZMG
        Vendor ID:    0x0001
        Product Name: ZedMini
        Product ID:   0x0001

        Description:  ZedMini
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_RPDO 1
#define OD_CNT_TPDO 11


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 3
#define OD_CNT_ARR_1016 1
#define OD_CNT_ARR_3000 1
#define OD_CNT_ARR_3800 1
#define OD_CNT_ARR_3801 1
#define OD_CNT_ARR_3802 1
#define OD_CNT_ARR_3803 1
#define OD_CNT_ARR_3804 1
#define OD_CNT_ARR_3805 1
#define OD_CNT_ARR_3806 1
#define OD_CNT_ARR_3807 1
#define OD_CNT_ARR_3808 1
#define OD_CNT_ARR_3809 1
#define OD_CNT_ARR_380A 1


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint8_t x1003_predefinedErrorField_sub0;
    uint32_t x1005_syncCOB_ID;
    uint32_t x1006_communicationCyclePeriod;
    uint16_t x100C_guardTime;
    uint8_t x100D_lifeTimeFactor;
    uint32_t x1014_COB_ID_EMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorId;
        uint32_t productCode;
        uint32_t revisionNumber;
    } x1018_identityObject;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_Client_Server;
        uint32_t COB_ID_Server_Client;
    } x1200_serverSdoParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t mappingEntry;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1804_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1805_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1806_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1807_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1808_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x1809_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint8_t compatibilityEntry;
        uint16_t eventTimer;
    } x180A_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A03_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A04_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A05_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A06_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A07_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A08_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A09_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInTPDO;
        uint32_t mappingEntry;
    } x1A0A_TPDOMappingParameter;
    uint8_t x3000_digital_Outputs1_sub0;
    uint8_t x3000_digital_Outputs1[OD_CNT_ARR_3000];
    uint8_t x3800_digital_Inputs1_sub0;
    uint8_t x3800_digital_Inputs1[OD_CNT_ARR_3800];
    uint8_t x3801_digital_Inputs2_sub0;
    uint8_t x3801_digital_Inputs2[OD_CNT_ARR_3801];
    uint8_t x3802_digital_Inputs3_sub0;
    uint8_t x3802_digital_Inputs3[OD_CNT_ARR_3802];
    uint8_t x3803_digital_Inputs4_sub0;
    uint8_t x3803_digital_Inputs4[OD_CNT_ARR_3803];
    uint8_t x3804_digital_Inputs5_sub0;
    uint8_t x3804_digital_Inputs5[OD_CNT_ARR_3804];
    uint8_t x3805_digital_Inputs6_sub0;
    uint8_t x3805_digital_Inputs6[OD_CNT_ARR_3805];
    uint8_t x3806_digital_Inputs7_sub0;
    uint8_t x3806_digital_Inputs7[OD_CNT_ARR_3806];
    uint8_t x3807_digital_Inputs8_sub0;
    uint8_t x3807_digital_Inputs8[OD_CNT_ARR_3807];
    uint8_t x3808_digital_Inputs9_sub0;
    uint8_t x3808_digital_Inputs9[OD_CNT_ARR_3808];
    uint8_t x3809_digital_Inputs10_sub0;
    int16_t x3809_digital_Inputs10[OD_CNT_ARR_3809];
    uint8_t x380A_digital_Inputs11_sub0;
    int16_t x380A_digital_Inputs11[OD_CNT_ARR_380A];
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H100C &OD->list[5]
#define OD_ENTRY_H100D &OD->list[6]
#define OD_ENTRY_H1014 &OD->list[7]
#define OD_ENTRY_H1016 &OD->list[8]
#define OD_ENTRY_H1017 &OD->list[9]
#define OD_ENTRY_H1018 &OD->list[10]
#define OD_ENTRY_H1200 &OD->list[11]
#define OD_ENTRY_H1400 &OD->list[12]
#define OD_ENTRY_H1600 &OD->list[13]
#define OD_ENTRY_H1800 &OD->list[14]
#define OD_ENTRY_H1801 &OD->list[15]
#define OD_ENTRY_H1802 &OD->list[16]
#define OD_ENTRY_H1803 &OD->list[17]
#define OD_ENTRY_H1804 &OD->list[18]
#define OD_ENTRY_H1805 &OD->list[19]
#define OD_ENTRY_H1806 &OD->list[20]
#define OD_ENTRY_H1807 &OD->list[21]
#define OD_ENTRY_H1808 &OD->list[22]
#define OD_ENTRY_H1809 &OD->list[23]
#define OD_ENTRY_H180A &OD->list[24]
#define OD_ENTRY_H1A00 &OD->list[25]
#define OD_ENTRY_H1A01 &OD->list[26]
#define OD_ENTRY_H1A02 &OD->list[27]
#define OD_ENTRY_H1A03 &OD->list[28]
#define OD_ENTRY_H1A04 &OD->list[29]
#define OD_ENTRY_H1A05 &OD->list[30]
#define OD_ENTRY_H1A06 &OD->list[31]
#define OD_ENTRY_H1A07 &OD->list[32]
#define OD_ENTRY_H1A08 &OD->list[33]
#define OD_ENTRY_H1A09 &OD->list[34]
#define OD_ENTRY_H1A0A &OD->list[35]
#define OD_ENTRY_H3000 &OD->list[36]
#define OD_ENTRY_H3800 &OD->list[37]
#define OD_ENTRY_H3801 &OD->list[38]
#define OD_ENTRY_H3802 &OD->list[39]
#define OD_ENTRY_H3803 &OD->list[40]
#define OD_ENTRY_H3804 &OD->list[41]
#define OD_ENTRY_H3805 &OD->list[42]
#define OD_ENTRY_H3806 &OD->list[43]
#define OD_ENTRY_H3807 &OD->list[44]
#define OD_ENTRY_H3808 &OD->list[45]
#define OD_ENTRY_H3809 &OD->list[46]
#define OD_ENTRY_H380A &OD->list[47]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_predefinedErrorField &OD->list[2]
#define OD_ENTRY_H1005_syncCOB_ID &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H100C_guardTime &OD->list[5]
#define OD_ENTRY_H100D_lifeTimeFactor &OD->list[6]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[7]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[8]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[9]
#define OD_ENTRY_H1018_identityObject &OD->list[10]
#define OD_ENTRY_H1200_serverSdoParameter &OD->list[11]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[12]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[13]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[14]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[15]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[16]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1804_TPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1805_TPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1806_TPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1807_TPDOCommunicationParameter &OD->list[21]
#define OD_ENTRY_H1808_TPDOCommunicationParameter &OD->list[22]
#define OD_ENTRY_H1809_TPDOCommunicationParameter &OD->list[23]
#define OD_ENTRY_H180A_TPDOCommunicationParameter &OD->list[24]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[25]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[26]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[27]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[28]
#define OD_ENTRY_H1A04_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A05_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A06_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A07_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H1A08_TPDOMappingParameter &OD->list[33]
#define OD_ENTRY_H1A09_TPDOMappingParameter &OD->list[34]
#define OD_ENTRY_H1A0A_TPDOMappingParameter &OD->list[35]
#define OD_ENTRY_H3000_digital_Outputs1 &OD->list[36]
#define OD_ENTRY_H3800_digital_Inputs1 &OD->list[37]
#define OD_ENTRY_H3801_digital_Inputs2 &OD->list[38]
#define OD_ENTRY_H3802_digital_Inputs3 &OD->list[39]
#define OD_ENTRY_H3803_digital_Inputs4 &OD->list[40]
#define OD_ENTRY_H3804_digital_Inputs5 &OD->list[41]
#define OD_ENTRY_H3805_digital_Inputs6 &OD->list[42]
#define OD_ENTRY_H3806_digital_Inputs7 &OD->list[43]
#define OD_ENTRY_H3807_digital_Inputs8 &OD->list[44]
#define OD_ENTRY_H3808_digital_Inputs9 &OD->list[45]
#define OD_ENTRY_H3809_digital_Inputs10 &OD->list[46]
#define OD_ENTRY_H380A_digital_Inputs11 &OD->list[47]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
